### ISSUE TITLE
tool.js inclusion error

### ISSUE THREAD

**Issue by bchalier** [inspector-apm/inspector-nova-link#1]
here : https://github.com/inspector-apm/inspector-nova-link/blob/d75d9c7dbb6a3c314132246c613bfd1b5fd85095/src/InspectorNovaLink.php#L17

the compiled js not being committed in the repo results in an error each time nova is loaded :

> file_get_contents([...]/vendor/inspector-apm/inspector-nova-link/src/../dist/js/tool.js): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_get_contents([...]/vendor/inspector-apm/inspector-nova-link/src/../dist/js/tool.js): failed to open stream: No such file or directory at [...]/vendor/laravel/nova/src/Http/Controllers/ScriptController.php:28)

**Comment by ilvalerione** [comment]
Hi @bchalier, what version of Laravel are you using?

**Comment by bchalier** [comment]
laravel : 6.17.1
php : 7.3.15
inspector-nova-link : 1.0.0

**Comment by ilvalerione** [comment]
A new version was released just now to fix this error.
